openapi: "3.0.2"
info:
  description: "API for the SCION Control Service"
  title: Control Service API
  version: "0.0.1"
servers:
  - url: http://{host}:{port}
    variables:
      host:
        default: "localhost"
      port:
        default: "30452"
tags:
  - name: segment
    description: Everything related to SCION path segments.
  - name: trust
    description: Everything related to SCION trust material.
  - name: common
    description: Common API exposed by SCION services.
paths:
  /segments:
    $ref: "./segments.yml#/paths/~1segments"
  /segments/{segment-id}:
    $ref: "./segments.yml#/paths/~1segments~1{segment-id}"
  /segments/{segment-id}/blob:
    $ref: "./segments.yml#/paths/~1segments~1{segment-id}~1blob"
  /signer:
    $ref: "./trust.yml#/paths/~1signer"
  /signer/blob:
    $ref: "./trust.yml#/paths/~1signer~1blob"
  /ca:
    $ref: "./trust.yml#/paths/~1ca"
  /trcs:
    $ref: "./trust.yml#/paths/~1trcs"
  /trcs/isd{isd}-b{base}-s{serial}:
    $ref: "./trust.yml#/paths/~1trcs~1isd{isd}-b{base}-s{serial}"
  /trcs/isd{isd}-b{base}-s{serial}/blob:
    $ref: "./trust.yml#/paths/~1trcs~1isd{isd}-b{base}-s{serial}~1blob"
  /certificates:
    $ref: "./trust.yml#/paths/~1certificates"
  /certificates/{chain-id}:
    $ref: "./trust.yml#/paths/~1certificates~1{chain-id}"
  /certificates/{chain-id}/blob:
    $ref: "./trust.yml#/paths/~1certificates~1{chain-id}~1blob"
  /info:
    $ref: "../common/process.yml#/paths/~1info"
  /log/level:
    $ref: "../common/process.yml#/paths/~1log~1level"
  /config:
    $ref: "../common/process.yml#/paths/~1config"
  /topology:
    $ref: "../common/process.yml#/paths/~1topology"
